#!/bin/sh

YT_DL="yt-dlp --add-metadata"
VIDP="mpv"
NTF="notify-send ytmpv"
MDIR="$HOME/Music"

while getopts qp:d:g:a:m:s: flag; do
  case "$flag" in
    q) NTF="true"      ;;
    p) VIDP="$OPTARG"  ;;
    d) MDIR="$OPTARG"  ;;
    g) YT_DL="$OPTARG" ;;
    a|s) ACTION="$OPTARG";;
    *) echo "ytmpv [-q] [-p PLAYER] [-d DIRECTORY] [-g DOWNLOADER] [(-a | -s) SUBCOMMAND]"; exit 1 ;;
  esac
done

SELITEM="$(dmenu -p "Video URL:" < /dev/null)"
if test -z "$ACTION"; then
[ "${SELITEM#*::}" = "$SELITEM" ] && PROMPTACTION="PLAY" || PROMPTACTION=${SELITEM%%::*}
ACTION="${PROMPTACTION:-$ACTION}"
fi

[ "$ACTION" = "SADA" ] && SELITEM="$(ytfzf -Il -D "${SELITEM#*::}" | head -n1)" ACTION=XAUD
[ "$ACTION" = "SAP"  ] && SELITEM="$(ytfzf -Il -D "${SELITEM#*::}" | head -n1)" ACTION=PLAY

SELURL="${SELITEM#*::}"

case "${ACTION:?}" in
	XAUD)
    SAVEDIR="$(find "$MDIR" -type d | dmenu -l 10 -p "Directory:")"
    FILENAME="$(dmenu -p "Filename:" < /dev/null)"
		$YT_DL "${SELURL:?}" -x --audio-format vorbis -P "${SAVEDIR:-$MDIR}"\
      -o "${FILENAME:-Song}"\
      && $NTF "Download Completed" || $NTF "Failure To Download"
		;;
	DOWN) $YT_DL "${SELURL:?}" && $NTF "Download Completed" || $NTF "Failed to Download" ;; 

	PLAY) $VIDP "${SELURL:?}" || $NTF "Failure to play URL" ;;

  *) printf "Unknown Action: %s" "$ACTION"; exit 1 ;;
esac
