#!/bin/sh

YT_DL="yt-dlp --add-metadata"
VIDP="mpv"
NTF="notify-send ytmpv"

SELITEM="$(dmenu -p "Video URL:" < /dev/null)"
[ -z "$SELITEM" ] && exit
SELURL="${SELITEM#*::}"
[ -z "$SELURL" ] && exit

case "$SELITEM" in
	XAUD::*)
		$YT_DL -x --audio-format vorbis -P "$HOME/Music" \
			-o "$(dmenu -p "Filename:" < /dev/null)" "$SELURL"\
			|| $NTF "Failure To Download"
		$NTF "Extracting Audio for: $SELURL"
		$NTF "Download Completed"
		;;

	DOWN::*)
		$NTF "Downloading $SELURL"
		$YT_DL "$SELURL" || $NTF "Failed to Download"
		$NTF "Download Completed"
		;;

	*)
		$NTF "Playing $SELITEM"
		$VIDP "$SELITEM" || $NTF "Failure to play URL"
		;;
esac
